version: "1.0"
info:
  model: int-scaffold
packages:
- name: AutoCommitTestProject
  gitServerName: moaa
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: moaaSoftwareAG
  gitBranch: main
services:
- serviceName: project.autocommittest.integrations:flow_2
  packages:
  - name: AutoCommitTestProject
    version: "1.0"
